'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Categoria
    Public Property IdCategoria As String
    Public Property Categoria1 As String
    Public Property Activos As String

    Public Overridable Property Productos As ICollection(Of Productos) = New HashSet(Of Productos)

End Class
