'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Proveedores
    Public Property Cod_Proveedor As String
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Telefono As Nullable(Of Long)
    Public Property Direccion As String
    Public Property CbuAlias As String
    Public Property Observacion As String

End Class
