'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property Id_Usuario As Integer
    Public Property Id_Perfil As Nullable(Of Integer)
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Dni As Nullable(Of Integer)
    Public Property Telefono As String
    Public Property Direccion As String
    Public Property Email As String
    Public Property Usuario1 As String
    Public Property Contraseña As String
    Public Property Activo As String

    Public Overridable Property Perfil As Perfil
    Public Overridable Property Venta_Cabecera As ICollection(Of Venta_Cabecera) = New HashSet(Of Venta_Cabecera)

End Class
