'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Venta_Detalle
    Public Property Id_Venta As Integer
    Public Property Codigo As String
    Public Property Id_Cabecera As Integer
    Public Property Precio As Nullable(Of Decimal)
    Public Property Cantidad As Nullable(Of Integer)
    Public Property Total As Nullable(Of Decimal)

    Public Overridable Property Productos As Productos
    Public Overridable Property Venta_Cabecera As Venta_Cabecera

End Class
