'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Venta_Cabecera
    Public Property Id_Cabecera As Integer
    Public Property Id_Cliente As String
    Public Property Id_Usuario As Nullable(Of Integer)
    Public Property Fecha As Nullable(Of Date)
    Public Property Total As Nullable(Of Decimal)

    Public Overridable Property Clientes As Clientes
    Public Overridable Property Usuario As Usuario
    Public Overridable Property Venta_Detalle As ICollection(Of Venta_Detalle) = New HashSet(Of Venta_Detalle)

End Class
